use_frameworks!
platform :ios, '13.0'


target 'SelectionMenu_Example' do
  pod 'SelectionMenu', :path => '../'
  pod 'SnapKit'

  target 'SelectionMenu_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 9.0.1'
  end
end
